# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

genoEM <- function(refCounts, altCounts, ploidy, h, eps, mrep, mdiff, returnAll) {
    .Call(`_tripsAndDipR_genoEM`, refCounts, altCounts, ploidy, h, eps, mrep, mdiff, returnAll)
}

genoEM_noise <- function(refCounts, altCounts, ploidy, h, eps, mrep, mdiff, returnAll) {
    .Call(`_tripsAndDipR_genoEM_noise`, refCounts, altCounts, ploidy, h, eps, mrep, mdiff, returnAll)
}

llh_calc_BB_noise <- function(refCounts, altCounts, tau, mixWeights, ploidy, h, eps) {
    .Call(`_tripsAndDipR_llh_calc_BB_noise`, refCounts, altCounts, tau, mixWeights, ploidy, h, eps)
}

